apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - fast
      initContainers:
        # First Init Container for waiting for PostgreSQL
        - name: wait-for-postgresql
          image: cgr.dev/chainguard/wait-for-it:latest
          args: ["postgres-postgresql.postgres.svc.cluster.local:5432", "--timeout=60"]
          envFrom:
            - secretRef:
                name: backend-secrets
        # Second Init Container for running migrations
        - name: run-migrations
          image: backend:0.7.1  # Same image as backend container
          command: ["/bin/sh", "-c", "python app/backend_pre_start.py && alembic upgrade head && python app/initial_data.py"]
          envFrom:
            - secretRef:
                name: backend-secrets  # Use the same secret for environment variables
      containers:
        - name: backend
          image: backend:0.7.1
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /api/v1/utils/health-check/
              port: 8000
            initialDelaySeconds: 15   # Initial delay before probe starts
            periodSeconds: 20         # Interval between probes
          readinessProbe:
            httpGet:
              path: /api/v1/utils/health-check/
              port: 8000
            initialDelaySeconds: 7    # Initial delay before probe starts
            periodSeconds: 10         # Interval between probes
          envFrom:
            - secretRef:
                name: backend-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          
